baseURL = "https://jacksalici.com/"
paginate = 10
theme = "salinger"
title = "jacksalici"

[params]
DateFormat = "January 2006"
author = "Jack Salici"
copyright = 'Jack Salici. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Some rights reserved</a>.'
dark = "off"
description = "Developer and designer based in Italy."
header = "Howdy, I'm Jack. ğŸ•ğŸŒµğŸ’»"
keywords = ["jack salici", "Portfolio", "giacomo salici", "salici", "developer", "coding", "maker"]
showHeaderOnHomepage = false
googleAnalytics = "G-TCJ26JMX8T"
enableEmoji = true


[permalinks]
  '/' = '/:slug/'
  'projects' = '/:slug/'


[[params.socialIcons]]
icon = "fab fa-github"
name = "github"
url = "https://github.com/jacksalici"


[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/jacksalici"

[[params.socialIcons]]
name = "email"
url = "mailto:hi@jacksalici.com"





[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "mailto:hey@jacksalici.com"
weight = 2
